#!/usr/bin/env bash
#MISE description="Generate or repair secrets/shared.env with strong random values (values never printed)."
set -euo pipefail

# secrets:generate -- create a complete gitignored secrets/shared.env without
# copying placeholder values from secrets/shared.env.example. Existing non-placeholder
# values are preserved so reruns do not rotate write-once secrets.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
REPO_ROOT="${MISE_PROJECT_ROOT:-$(cd -- "${SCRIPT_DIR}" >/dev/null 2>&1 && { git rev-parse --show-toplevel 2>/dev/null || pwd -P; })}"

# shellcheck source=/dev/null
. "${REPO_ROOT}/.config/mise/lib/common.sh"
# shellcheck source=/dev/null
. "${REPO_ROOT}/.config/mise/lib/secrets.sh"
install_err_trap

readonly SECRETS_DIR="${REPO_ROOT}/secrets"
readonly SHARED_ENV="${SECRETS_DIR}/shared.env"
tmp=""

cleanup_tmp() {
  [[ -z "${tmp}" ]] || rm -f -- "${tmp}"
}

main() {
  require_cmd openssl
  mkdir -p -- "${SECRETS_DIR}"

  declare -A existing=()
  local line key value
  if [[ -f "${SHARED_ENV}" ]]; then
    while IFS= read -r line || [[ -n "${line}" ]]; do
      [[ "${line}" =~ ^[[:space:]]*# ]] && continue
      [[ "${line}" =~ ^[[:space:]]*$ ]] && continue
      [[ "${line}" == *=* ]] || continue
      key="${line%%=*}"
      value="${line#*=}"
      value="${value%$'\r'}"
      [[ "${key}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
      existing["${key}"]="${value}"
    done <"${SHARED_ENV}"
  fi

  tmp="$(mktemp "${SECRETS_DIR}/shared.env.tmp.XXXXXX")"
  chmod 600 "${tmp}" # macOS/BSD chmod rejects the `--` separator
  add_exit_trap cleanup_tmp

  local generated=0 preserved=0 optional=0
  local secret_value fallback_key
  {
    printf '# secrets/shared.env -- GITIGNORED plaintext input for fnox sealing.\n'
    printf '# Generated by mise run secrets:generate; values are never printed by tasks.\n'
    printf '# Rerunning preserves non-placeholder values and fills only missing placeholders.\n\n'
    printf '# --- fnox+age managed secrets ---\n'
    for key in "${AI_INFRA_FNOX_SECRET_KEYS[@]}"; do
      secret_value="${existing[${key}]:-}"

      # Backward-compatible aliases from the older example file.
      if ai_infra_secret_is_placeholder "${secret_value}"; then
        case "${key}" in
        LANGFUSE_ADMIN_PASSWORD) fallback_key="LANGFUSE_INIT_USER_PASSWORD" ;;
        LANGFUSE_PUBLIC_KEY) fallback_key="LANGFUSE_INIT_PROJECT_PUBLIC_KEY" ;;
        LANGFUSE_SECRET_KEY) fallback_key="LANGFUSE_INIT_PROJECT_SECRET_KEY" ;;
        *) fallback_key="" ;;
        esac
        if [[ -n "${fallback_key}" && -n "${existing[${fallback_key}]+x}" ]] &&
          ! ai_infra_secret_is_placeholder "${existing[${fallback_key}]}"; then
          secret_value="${existing[${fallback_key}]}"
        fi
      fi

      if ai_infra_secret_is_placeholder "${secret_value}"; then
        secret_value="$(ai_infra_generate_secret_value "${key}")"
        generated=$((generated + 1))
      else
        preserved=$((preserved + 1))
      fi
      printf '%s=%s\n' "${key}" "${secret_value}"
    done

    printf '\n# --- optional plaintext-only Docker Hub cache credentials (not sealed) ---\n'
    for key in "${AI_INFRA_SHARED_ENV_OPTIONAL_KEYS[@]}"; do
      secret_value="${existing[${key}]:-}"
      if ai_infra_secret_is_placeholder "${secret_value}"; then
        printf '# %s=\n' "${key}"
      else
        printf '%s=%s\n' "${key}" "${secret_value}"
        optional=$((optional + 1))
      fi
    done
  } >"${tmp}"

  mv -f -- "${tmp}" "${SHARED_ENV}"
  clear_exit_traps
  chmod 600 "${SHARED_ENV}" # macOS/BSD chmod rejects the `--` separator

  info "wrote secrets/shared.env with ${#AI_INFRA_FNOX_SECRET_KEYS[@]} fnox-managed secret key(s)"
  info "preserved ${preserved} existing non-placeholder value(s); generated ${generated} new random value(s)"
  if ((optional)); then
    info "preserved ${optional} optional Docker Hub cache credential value(s) (not sealed into fnox)"
  else
    info "optional Docker Hub cache credentials are unset; cache:up will run anonymously unless you fill them in"
  fi
  warn "LANGFUSE_SALT and LANGFUSE_ENCRYPTION_KEY are write-once after first boot; preserve backups if reusing old data."
}

main "$@"
